language: node_js
node_js:
  - '12.16.1'
services:
  - docker
  # Travis-CI Caching
cache:
  yarn: true
  directories:
    - node_modules # 缓存node_modules文档夹
addons:
  ssh_known_hosts: $server_ip
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_a61bf7cd320c_key -iv $encrypted_a61bf7cd320c_iv -in authorized_keys.enc -out ~/.ssh/authorized_keys -d
  - chmod 600 ~/.ssh/authorized_keys
install:
  - yarn install
script:
  - yarn build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t lostimever/vue3-ts:latest .
  - docker push lostimever/vue3-ts:latest
after_success:
  - ssh -o "StrictHostKeyChecking no" -i ~/.ssh/authorized_keys -p $server_port root@$server_ip "cd /wlf/dockerfiles/vue3-ts;docker-compose pull info;docker-compose stop info;docker-compose rm info;docker-compose up -d info;exit"
